# Specifies the Minecraft version.
# Defaults to the version specified in the modpack's metadata file, if present.
#
# minecraft.version=26.1.2

# Specifies the directory for Fabric Loader-related files.
# Defaults to ".fabric".
#
# fabric-loader.root=.fabric

# Specifies the Fabric Loader version.
# Defaults to the version specified in the modpack's metadata file, if present;
# otherwise, defaults to "0.19.0".
#
# fabric-loader.version=0.19.0

# Specifies the Fabric Installer version.
# Defaults to "1.1.1".
#
# fabric-installer.version=1.1.1

# Specifies the direct URL for downloading the Fabric Installer.
# If not provided, will be resolved using minecraft.version, fabric-loader.version, and fabric-installer.version.
#
# fabric-installer.url=https://meta.fabricmc.net/v2/versions/loader/26.1.2/0.19.0/1.1.1/server/jar

# Specifies the directory for Packwiz-related files.
# Defaults to ".packwiz".
#
# packwiz.root=.packwiz

# Specifies the direct URL of your modpack's metadata file, as used by Packwiz.
#
# packwiz.url=https://github.com/me/my-modpack/raw/refs/heads/main/pack.toml

# Specifies the packwiz-installer-bootstrap version.
# Defaults to "0.0.3".
#
# packwiz.bootstrap.version=0.0.3

# Specifies the direct URL for downloading packwiz-installer-bootstrap.
# If not provided, it will be resolved using packwiz.bootstrap.version.
#
# packwiz.bootstrap.url=https://github.com/packwiz/packwiz-installer-bootstrap/releases/download/v0.0.3/packwiz-installer-bootstrap.jar

# Indicates whether the contents of "usercache.json" should always be preserved.
# When enabled, this option prevents future evictions from the user cache by
# setting the expiration date of every entry to the start of the next century.
# Defaults to "false".
#
# usercache.keep=false

# Specifies additional arguments to pass to the JVM when starting the server.
#
# java.args=-Xmx2G

# Specifies whether to enable Git integration.
# When enabled, the launcher will automatically pull changes from the remote (if configured)
# before starting the server, commit all changes made while the server was running, and push
# them back to the remote (once again, if one is configured).
# Defaults to "true" if the launcher is run inside a Git repository;
# otherwise, defaults to "false".
#
# git.enable=true

# Specifies the maximum number of commits allowed in the active branch.
# When the limit is reached, all previous history will be compacted into a single commit.
# Enable with caution, as this will lead to constant history rewrites and potential repository corruption.
# Defaults to "0" (disabled).
#
# git.limit=0

# Overrides the number of commits kept when the history is compacted after reaching the configured git.limit.
# Defaults to "1".
#
# git.keep=1
